import os

class config:
    SECRET_KEY = OS.ENVIRON.GET('SECRET_KEY') OR 'CHAVE-SECRETA-GERADA-ALEATORIAMENTE'
    SQLALCHEMY_DATABASE_URI = OS.ENVIRON.GET('DATABASE_URL') OR 'sqlite:///pdv.db'
    SQLALCHEMY_TRACK_MODIFICATIONS = False